# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


spring:
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mariadb://localhost:3306/chsp
        name:
        username: chsp
        password:
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: false
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
            hibernate.javax.cache.uri: ${spring.cache.jcache.config}
            hibernate.cache.region.factory_class: com.evpa.chsp.config.jcache.SpringCacheRegionFactory
    cache:
        jcache:
            config: ehcache.xml
    data:
        elasticsearch:
            cluster-name:
            cluster-nodes:
            properties:
                path:
                  logs: /tmp/elasticsearch/log
                  data: /tmp/elasticsearch/data
    mail:
        host: smtp.gmail.com
        port: 587
        username: pavlenko.evgeny
        password: b5kH5hfNHX9d51
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
    thymeleaf:
        cache: false

liquibase:
    contexts: prod

server:
    port: 8081
    #port: 7070
    ##compression:
    ##    enabled: true
    ##    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    ##    min-response-size: 1024

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    http:
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 1461
    cache: # Hibernate 2nd level cache, used by CacheConfiguration
        ehcache:
            maxBytesLocalHeap: 256M
    security:
        authentication:
            jwt:
                secret: 41a2d423980af7f2bb3a1a4f5bdd5fce0fa872a5
                # Token is valid 24 hours
                tokenValidityInSeconds: 86400
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: chsp@localhost
        baseUrl: http://192.168.1.100:8081
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: chsp
        prometheus:
            enabled: false
            endpoint: /prometheusMetrics
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
    #ribbon:
            # comma separated list of profiles to show a ribbon on the GUI
            #displayOnActiveProfiles: Production
